apiVersion: apps/v1
kind: Deployment
metadata:
  name: directory-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: directory-app
  template:
    metadata:
      labels:
        app: directory-app
    spec:
      containers:
          - name: directory-container
            image: directory:latest
            ports:
              - containerPort: 8080
            env:
              - name: SPRING_DATASOURCE_URL
                value: jdbc:mysql://mysql-service:3306
              - name: SPRING_DATASOURCE_USERNAME
                valueFrom:
                  secretKeyRef:
                    name: root
                    key: username
              - name: SPRING_DATASOURCE_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: password
                    key: password