apiVersion: apps/v1
kind: Deployment
metadata:
  name: directory-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: directory
  template:
    metadata:
      labels:
        app: directory
    spec:
      containers:
          - name: directory-container
            image: directory:latest
            imagePullPolicy: Always
            ports:
              - containerPort: 8080
            env:
              - name: SPRING_DATASOURCE_URL
                value: {{ include "my-spring-app.fullMySQLConnectionURL" . | quote }}
#              - name: SPRING_DATASOURCE_USERNAME
#                valueFrom:
#                  secretKeyRef:
#                    name: {{ .Release.Name }}-mysql-username
#                    key: username
#              - name: SPRING_DATASOURCE_PASSWORD
#                valueFrom:
#                  secretKeyRef:
#                    name: {{ .Release.Name }}-mysql-password
#                    key: password
